leftnav:
- identifier: e7b4ffce-84f9-e9d7-e492-0f4fb208f8c8
  name: Syllabus and Calendar
  url: /pages/syllabus
  weight: 10
- identifier: 04f2820d-a589-7975-b509-cecac99f2a14
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: d9bdd530-8a3e-680a-72ee-4587b2c8dde3
  name: Assignments
  url: /pages/assignments
  weight: 30
